import React from "react";

const BankOptions = [
  { label: "Select an option" },
  { value: "Access Bank", label: "Access Bank Plc" },
  { value: "Fidelity Bank", label: "Fidelity Bank Plc" },
  { value: "FCMB", label: "First City Monument Bank Limited" },
  { value: "First Bank", label: "First Bank of Nigeria Limited" },
  { value: "Guaranty Trust Bank", label: "Guaranty Trust Bank" },
  { value: "Union Bank", label: "Union Bank of Nigeria Plc" },
  { value: "UBA", label: "United Bank for Africa Plc" },
  { value: "Zenith Bank", label: "Zenith Bank Plc" },
  { value: "Citibank", label: "Citibank Nigeria Limited" },
  { value: "Ecobank", label: "Ecobank Nigeria" },
  { value: "Heritage Bank", label: "Heritage Bank Plc" },
  { value: "Keystone Bank", label: "Keystone Bank Limited" },
  { value: "Optimus Bank", label: "Optimus Bank Limited" },
  { value: "Polaris Bank", label: "Polaris Bank Limited" },
  { value: "Stanbic IBTC", label: "Stanbic IBTC Bank Plc" },
  { value: "Standard Chartered", label: "Standard Chartered" },
  { value: "Sterling Bank", label: "Sterling Bank Plc" },
  { value: "Titan Trust Bank", label: "Titan Trust bank" },
  { value: "Unity Bank", label: "Unity Bank Plc" },
  { value: "Wema Bank", label: "Wema Bank Plc" },
  { value: "Globus Bank", label: "Globus Bank Limited" },
  { value: "Parallex Bank", label: "Parallex Bank Limited" },
  { value: "PremiumTrust Bank", label: "PremiumTrust Bank Limited" },
  { value: "Providus Bank", label: "Providus Bank Limited" },
  { value: "SunTrust Bank", label: "SunTrust Bank Nigeria Limited" },
  { value: "Jaiz Bank", label: "Jaiz Bank Plc" },
  { value: "Lotus Bank", label: "Lotus Bank" },
  { value: "TAJBank", label: "TAJBank Limited" },
  {
    value: "Mutual Trust Microfinance Bank",
    label: "Mutual Trust Microfinance Bank",
  },
  { value: "Rephidim Microfinance Bank", label: "Rephidim Microfinance Bank" },
  {
    value: "Shepherd Trust Microfinance Bank",
    label: "Shepherd Trust Microfinance Bank",
  },
  {
    value: "Empire Trust Microfinance Bank",
    label: "Empire Trust Microfinance Bank",
  },
  {
    value: "Finca Microfinance Bank",
    label: "Finca Microfinance Bank Limited",
  },
  {
    value: "Fina Trust Microfinance Bank",
    label: "Fina Trust Microfinance Bank",
  },
  { value: "Accion Microfinance Bank", label: "Accion Microfinance Bank" },
  { value: "Peace Microfinance Bank", label: "Peace Microfinance Bank" },
  { value: "Infinity Microfinance Bank", label: "Infinity Microfinance Bank" },
  {
    value: "Pearl Microfinance Bank",
    label: "Pearl Microfinance Bank Limited",
  },
  {
    value: "Covenant Microfinance Bank",
    label: "Covenant Microfinance Bank Ltd",
  },
  {
    value: "Advans La Fayette Microfinance Bank",
    label: "Advans La Fayette Microfinance Bank",
  },

  {
    value: "FairMoney Microfinance Bank",
    label: "FairMoney Microfinance Bank",
  },
  { value: "Sparkle Bank", label: "Sparkle Bank" },
  { value: "Kuda Bank", label: "Kuda Bank" },
  {
    value: "Moniepoint Microfinance Bank",
    label: "Moniepoint Microfinance Bank",
  },
  { value: "Opay", label: "Opay" },
  { value: "Dot Microfinance Bank", label: "Dot Microfinance Bank" },
  { value: "Palmpay", label: "Palmpay" },
  { value: "Rubies Bank", label: "Rubies Bank" },
  { value: "VFD Microfinance Bank", label: "VFD Microfinance Bank" },
  { value: "Mint Finex MFB", label: "Mint Finex MFB" },
  { value: "Mkobo MFB", label: "Mkobo MFB" },
  { value: "Raven bank", label: "Raven bank" },
  { value: "Rex Microfinance Bank", label: "Rex Microfinance Bank" },
  { value: "Coronation Merchant Bank", label: "Coronation Merchant Bank" },
  { value: "FBNQuest Merchant Bank", label: "FBNQuest Merchant Bank" },
  { value: "FSDH Merchant Bank", label: "FSDH Merchant Bank" },
  { value: "Greenwich Merchant Bank", label: "Greenwich Merchant Bank" },
  { value: "Rand Merchant Bank", label: "Rand Merchant Bank" },
  { value: "Nova Merchant Bank", label: "Nova Merchant Bank" },
  { value: "SunTrust Bank Nig", label: "SunTrust Bank Nigeria limited" },
  { value: "Stanbic Ibtc NIB", label: "Stanbic Ibtc NIB" },
];

export default BankOptions;
